name 'filebeat_test'
maintainer 'Virender Khatri'
maintainer_email 'vir.khatri@gmail.com'
license 'Apache-2.0'
description 'Installs/Configures Filebeat Test Cookbook Resources'
version '0.0.1'
source_url 'https://github.com/vkhatri/chef-filebeat'
issues_url 'https://github.com/vkhatri/chef-filebeat/issues'
chef_version '>= 12.14'

depends 'filebeat'
